### ISSUE TITLE
The wrong placement of CXR numpy array

### ISSUE THREAD

**Issue by ChisamXz** [sgfin/adversarial-medicine#1]
Hi,
I guess you placed the CXR numpy array as the DR numpy array by mistake.
Just for a reminder, thank you for your sharing!

**Comment by sgfin** [comment]
Thanks for letting me know.  I'll try to fix this right away.  To be clear, you're saying that the numpy data folder label "DR" appears to contain numpy files with CXR images instead?  Or the other way around?

**Comment by ChisamXz** [comment]
Sorry for the confusing. 
The numpy data for the CXR images is wrong.

**Comment by ChisamXz** [comment]
Besides, may I ask what's the "_model_prediction_original_test_images.npy" in Line653 of 'patch_derm_v3.py' in the patch attacks. 
I didn't find any reference of how to generate the numpy data. If possible, would it be convenient for you to share the file or explain what's in it?

**Comment by sgfin** [comment]
Thanks so much again for the feedback.  I've updated the numpy files, and believe that that should resolve the issues with the CXR images.  In addition, I've added numpy arrays of the model predictions as well as of the adversarial images.  Of course, model predictions can also be generated trivially by loading the models themselves into keras and predicting on the numpy arrays.

I am guessing that the "_model_prediction_original_test_images.npy" is the array of predictions on the clean images, which can either be loaded from the numpy arrays or generated by loading the models and calling `model.predict()`.  That said, my collaborator was the one who wrote that particular notebook, and I know he was hoping to clean it up a bit anyway.  I've reached out to him to take a look and confirm.  Thanks!

**Comment by hwc27** [comment]
In patch_derm_v3.py, we are reporting how the probability prediction is changed by the patch. So we need to run the prediction on the unpatched original images. Since this prediction does not depend on the patch, we can run it once and store the prediction result. This speeds up the code quite a bit. 

I just added the files: https://github.com/sgfin/adversarial-medicine/tree/master/patch_attacks/etc_saved_files

Each npy file is np array with shape (n_test, 2) where row i corresponds to the probability that the test image i is negative/positive example.

**Comment by ChisamXz** [comment]
@sgfin @hwc27 Thank you for your detailed answers. That helps me a lot! Thank you for the sharing!

**Comment by hwc27** [comment]
@ChisamXz I just want to let you know that the code is cleaned and updated quite a bit for easier use. `patch_derm_v3.py` file is now renamed as `craft_attack_patch.py`. Also please check out the updated README. It contains detailed instruction for using `craft_attack_patch.py`.

**Comment by ChisamXz** [comment]
@hwc27 Thank you for the update and reminding! I could execute the patch attack successfully now.

**Comment by sgfin** [comment]
Awesome. Closing the issue now.
