### ISSUE TITLE
training/testing splitting information is not included

### ISSUE THREAD

**Issue by ghost** [sgfin/adversarial-medicine#3]
Hello. Thanks for sharing your great work. I want to run these pretrained models on testing images, but I couldn't find the lists of training/testing splitting.

Could you please share the training and testing filename lists for all 6 pretrained models?

**Comment by sgfin** [comment]
Unfortunately, I've migrated around servers several times since doing this project and -- to my everlasting shame -- I can't find the files that contain all the original file splits.  I'll update this issue later if I ever find them.  Sorry!
